Solución Taller Complex Numbers
Nombre: Camilo Aguirre
CNYT-2025-2

## Exercise 1: Complex Internal Product for Column Vectors

Given two complex column vectors:

$$ \mathbf{a} = \begin{bmatrix} 1 + 2i \\ 3 - 4i \end{bmatrix}, \quad \mathbf{b} = \begin{bmatrix} 2 - i \\ -1 + 3i \end{bmatrix} $$

Calculate the complex internal product $ \langle \mathbf{a}, \mathbf{b} \rangle $.

In [8]:
import numpy as np

# Definir los vectores columna como arreglos de NumPy con dtype=complex
a = np.array([1+2j, 3-4j], dtype=complex)
b = np.array([2-1j, -1+3j], dtype=complex)

# Producto interno complejo: conj(a)^T * b
inner_product = np.vdot(a, b)   # vdot ya toma el conjugado del primero
# También se puede usar: inner_product = np.conjugate(a).T @ b

print("Vector a:", a)
print("Vector b:", b)
print("Producto interno complejo <a,b> =", inner_product)



Vector a: [1.+2.j 3.-4.j]
Vector b: [ 2.-1.j -1.+3.j]
Producto interno complejo <a,b> = (-15+0j)


## Exercise 2: Complex Internal Product for Square Complex Matrices

Given two square complex matrices:

$$ A = \begin{bmatrix} 1+i & 2-2i \\ 3+3i & 4-i \end{bmatrix}, \quad B = \begin{bmatrix} 1-2i & 3+i \\ 4-4i & 2+2i \end{bmatrix} $$

Calculate the complex internal product $ \langle A, B \rangle $.


In [3]:
import numpy as np

# Definir matrices complejas
A = np.array([[1+1j, 2-2j],
              [3+3j, 4-1j]], dtype=complex)

B = np.array([[1-2j, 3+1j],
              [4-4j, 2+2j]], dtype=complex)

# Producto interno: sum(conj(A_ij) * B_ij)
inner_product = np.vdot(A, B)   # vdot aplanará matrices y hace conj(A)*B
# Otra forma: inner_product = np.sum(np.conjugate(A) * B)

print("Producto interno complejo <A,B> =", inner_product)


Producto interno complejo <A,B> = (9-9j)


# Exercises on eigenvalues and eigenvectors

## Exercise 1: Compute Eigenvalues and Eigenvectors of a Real Matrix

Compute the eigenvalues and eigenvectors of the following real matrix:

$$
A = \begin{pmatrix}
4 & 1 \\
2 & 3
\end{pmatrix}
$$

**Hint:** Use `numpy.linalg.eig`.

In [4]:
import numpy as np

# Matriz A
A = np.array([[4, 1],
              [2, 3]], dtype=float)

# Cálculo con numpy
evals, evecs = np.linalg.eig(A)

print("Matriz A:\n", A)
print("\nAutovalores (eigenvalues):", evals)
print("\nAutovectores (columnas):\n", evecs)


Matriz A:
 [[4. 1.]
 [2. 3.]]

Autovalores (eigenvalues): [5. 2.]

Autovectores (columnas):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


## Exercise 2: Eigenvalues and Eigenvectors of a Complex Matrix

Compute the eigenvalues and eigenvectors of the following complex matrix:

$$
B = \begin{pmatrix}
1 + 2i & 2 + 3i \\
4 + 5i & 6 + 7i
\end{pmatrix}
$$

where \(i\) is the imaginary unit.

**Hint:** Ensure your matrix is defined with complex numbers in Python using `dtype=complex`.

In [5]:
import numpy as np

# Definir la matriz compleja B (asegúrate dtype=complex)
B = np.array([[1+2j, 2+3j],
              [4+5j, 6+7j]], dtype=complex)

# Calcular eigenvalores y eigenvectores
evals_B, evecs_B = np.linalg.eig(B)

# Imprimir resultado
np.set_printoptions(precision=6, suppress=False)
print("Matriz B:\n", B)
print("\nEigenvalores (values):\n", evals_B)
print("\nEigenvectores (columnas):\n", evecs_B)

# Verificación numérica: T * v = lambda * v (para cada autovector)
for i in range(len(evals_B)):
    lhs = B @ evecs_B[:, i]
    rhs = evals_B[i] * evecs_B[:, i]
    print(f"\nVerificación autovector {i+1}:")
    print("B @ v =", lhs)
    print("lambda * v =", rhs)
    print("diferencia (Bv - lambda v) =", lhs - rhs)


Matriz B:
 [[1.+2.j 2.+3.j]
 [4.+5.j 6.+7.j]]

Eigenvalores (values):
 [-0.255195-0.093636j  7.255195+9.093636j]

Eigenvectores (columnas):
 [[ 0.828068+0.j        0.352998+0.047827j]
 [-0.559984-0.02686j   0.934401+0.j      ]]

Verificación autovector 1:
B @ v = [-0.211319-0.077537j  0.14039 +0.059289j]
lambda * v = [-0.211319-0.077537j  0.14039 +0.059289j]
diferencia (Bv - lambda v) = [5.273559e-16-2.775558e-17j 8.604228e-16-6.591949e-16j]

Verificación autovector 2:
B @ v = [2.126146+3.557025j 6.779262+8.497103j]
lambda * v = [2.126146+3.557025j 6.779262+8.497103j]
diferencia (Bv - lambda v) = [ 1.332268e-15+0.j -8.881784e-16+0.j]


## Exercise 3: Symmetric Matrix Eigendecomposition

Compute the eigenvalues and eigenvectors of the following symmetric matrix:

$$
C = \begin{pmatrix}
5 & 4 \\
4 & 5
\end{pmatrix}
$$

Discuss the properties of the eigenvectors and eigenvalues for symmetric matrices based on your results.

In [6]:
import numpy as np

C = np.array([[5, 4],
              [4, 5]], dtype=float)

evals_C, evecs_C = np.linalg.eig(C)

print("Matriz C:\n", C)
print("Eigenvalores:", evals_C)
print("Eigenvectores (columnas):\n", evecs_C)

# Normalizar eigenvectores (opcional)
evecs_C_norm = evecs_C / np.linalg.norm(evecs_C, axis=0)
print("Eigenvectores normalizados (columnas):\n", evecs_C_norm)

# Comprobación ortogonalidad
dot01 = np.dot(evecs_C_norm[:,0].conj(), evecs_C_norm[:,1])
print("Producto punto entre eigenvectores normalizados (≈0):", dot01)


Matriz C:
 [[5. 4.]
 [4. 5.]]
Eigenvalores: [9. 1.]
Eigenvectores (columnas):
 [[ 0.707107 -0.707107]
 [ 0.707107  0.707107]]
Eigenvectores normalizados (columnas):
 [[ 0.707107 -0.707107]
 [ 0.707107  0.707107]]
Producto punto entre eigenvectores normalizados (≈0): -4.266421588589642e-17


## Exercise 4: Plotting Matrix Transformations

Consider the matrix:

$$
T = \begin{pmatrix}
2 & 1 \\
1 & 3
\end{pmatrix}
$$

1. Plot the unit circle.
2. Apply the matrix \(T\) to transform the unit circle.
3. Plot the transformed figure.
4. Show graphically that the eigenvectors are only multiplied by an escalar when transformed. (Plot the eigen vectors and the transformed ones) 

Explain how the matrix \(T\) transforms the unit circle based on the resulting plot.

**Hint:** Use `numpy` for matrix operations and `matplotlib` for plotting.

In [7]:
import numpy as np
import matplotlib.pyplot as plt

# Definir la matriz T
T = np.array([[2, 1],
              [1, 3]])

# Generar puntos de la circunferencia unidad
theta = np.linspace(0, 2*np.pi, 200)
circle = np.array([np.cos(theta), np.sin(theta)])  # shape (2,200)

# Aplicar transformación lineal T a todos los puntos
transformed_circle = T @ circle

# Calcular autovalores y autovectores de T
evals, evecs = np.linalg.eig(T)

# Normalizar los eigenvectores para graficarlos mejor
evecs_norm = evecs / np.linalg.norm(evecs, axis=0)

# Transformar los eigenvectores (deben quedar multiplicados por λ)
transformed_evecs = T @ evecs_norm

# ---------------- PLOTEO ----------------
plt.figure(figsize=(8,8))
plt.axhline(0, color="gray", linewidth=0.5)
plt.axvline(0, color="gray", linewidth=0.5)

# Circunferencia unidad
plt.plot(circle[0], circle[1], 'b', label="Unit circle")

# Circunferencia transformada
plt.plot(transformed_circle[0], transformed_circle[1], 'r', label="Transformed circle")

# Eigenvectores originales (azules con flecha)
for i in range(evecs_norm.shape[1]):
    plt.quiver(0, 0, evecs_norm[0,i], evecs_norm[1,i],
               angles="xy", scale_units="xy", scale=1, color="blue", width=0.008)

# Eigenvectores transformados (rojos con flecha)
for i in range(transformed_evecs.shape[1]):
    plt.quiver(0, 0, transformed_evecs[0,i], transformed_evecs[1,i],
               angles="xy", scale_units="xy", scale=1, color="red", width=0.008)

plt.gca().set_aspect("equal", adjustable="box")
plt.legend()
plt.title("Transformación de la unidad por T")
plt.show()

# ---------------- EXPLICACIÓN ----------------
print("Eigenvalores:", evals)
print("Eigenvectores (columnas):\n", evecs)


ModuleNotFoundError: No module named 'matplotlib'

## Exercise 5: Diagonal Matrix Eigendecomposition

Compute the eigenvalues and eigenvectors of the following diagonal matrix:

$$
D = \begin{pmatrix}
7 & 0 \\
0 & -3
\end{pmatrix}
$$

Discuss the significance of the eigenvalues and eigenvectors for diagonal matrices.


In [ ]:
import numpy as np

# Matriz diagonal D
D = np.array([[7, 0],
              [0, -3]], dtype=float)

# Cálculo de eigenvalores y eigenvectores
evals_D, evecs_D = np.linalg.eig(D)

print("Matriz D:\n", D)
print("\nEigenvalores:", evals_D)
print("\nEigenvectores (columnas):\n", evecs_D)

# Verificación numérica: D * v = lambda * v
for i in range(len(evals_D)):
    lhs = D @ evecs_D[:, i]
    rhs = evals_D[i] * evecs_D[:, i]
    print(f"\nVerificación autovector {i+1}:")
    print("D @ v =", lhs)
    print("lambda * v =", rhs)
    print("D@v - lambda*v =", lhs - rhs)
